### PR TITLE
Support for variable pen raising/lowering speed and other fixes

### PR DESCRIPTION
**Pull request by Yura80**
- After building my EggBot with EggDuino firmware, I noticed that quick servo moves destroy the tips of markers, making the lines very think. To fix this, I've added the support for configurable servo rate using VarSpeedServo library. 
- According to EBB protocol specs (http://www.schmalzhaus.com/EBB/EBBCommands.html), command "SP,1" moves pen up and "SP,0" moves pen down. In EggDuino up/down was reversed everywhere. This commit fixes this. 
- Included pin definitions for Protoneer CNC Shield which is available very cheap on eBay
- Added instructions for patching the new version of EggBot extension
- Engraver support

### CODE REVIEW

**Comment by dansche** [comment]
I tried to upload to Arduino with the CNC Board, but i get allways errors:

The Errors are as follows:
C:\3D Printer\eggbot one piece\duinomastercnc\EggDuino-master\EggDuino\EggDuino.ino: In function 'void setup()':

EggDuino:125: error: 'makeComInterface' was not declared in this scope

   makeComInterface();

                    ^

EggDuino:126: error: 'initHardware' was not declared in this scope

   initHardware();

                ^

C:\3D Printer\eggbot one piece\duinomastercnc\EggDuino-master\EggDuino\EggDuino.ino: In function 'void loop()':

EggDuino:130: error: 'moveOneStep' was not declared in this scope

   moveOneStep();

               ^

exit status 1
'makeComInterface' was not declared in this scope



What do i do wrong ?

Thanks for your help.

**Comment by Yura80** [comment]
I've added the missing prototypes. Please try now.

**Comment by jbabio** [comment]
I've tried this branch and works nice. The only thing you have to take into acouunt is that, if you set servo speed to slow, you'll get "ebb timeouts" when you send commands to raise/lower the pen and this timeouts cause the prints to pause. Those timeouts annoyed me till I identified their reason.

**Comment by MicDiFebo** [comment]
Hi Yura,
I struggeling with the servo in eggDuino, I simply cannot move it via serial commands like TP - the serial communication itself works, i get the version-reply on "v" and can move a motor. But the servo refuses to work. I recognized that it is "under fire" means it moves to an initial position when starting up the board and it holds the position when I try to move the servo manually.

I tried differend boards and servos and also wrote a short sketch to move only the servo, which was no problem. Now I become a bit desparate, because I simply have no more idea...do You have one?

Thanks in Advance and Greetz
Mic

**Comment by druckgott** [comment]
Where can I download your updated source as complete file?

**Comment by jmerc77** [comment]
found a way to patch eggbot 2.8.5 released in 2021 supplied with [axidraw 3.2.0 (zip linked)](https://cdn.evilmadscientist.com/dl/ad/public/ad-ink_320_r0.zip) on windows.
works on inkscape 1.1.2.

basically it allows manual port selection in the options tab.
I have the modified files if you want to add them:
[egg bot fix for eggduino.zip](https://github.com/cocktailyogi/EggDuino/files/8241702/egg.bot.fix.for.eggduino.zip)

**Comment by jmerc77** [comment]
just found out some of the generators etc. did not like inkscape 1.1.2.
0.92.4 works with eggbot v2.8.1 with these fixes:
[egg bot fix for eggduino.zip](https://github.com/cocktailyogi/EggDuino/files/8246871/egg.bot.fix.for.eggduino.zip)
